version: '3'
services:
  auth:
    image: $IMAGE
    container_name: auth
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
      - 5051:5051
      - 5000:5000

networks:
  default:
    external:
      name: $NETWORK